variables:
  GIT_STRATEGY: clone

stages:
  - build
  - deploy

Merge:
  stage: build
  image: sfy-search-registry-build.artifactory.packages.install-os.multis.p.fti.net/build/docker
  script:
    - git clone --single-branch -b stemcell4cs-3586.x https://github.com/jyriok/bosh-linux-stemcell-builder
    - cd bosh-linux-stemcell-builder/ci/docker
    - sudo ./run os-image-stemcell-builder


