variables:
  GIT_STRATEGY: clone

stages:
  - build
  - deploy

build-doc:
  stage: build
  image: sfy-search-registry-build.artifactory.packages.install-os.multis.p.fti.net/build/docker
  script:
    - uname -a

